apiVersion: v1
kind: Service
metadata:
  name: live-todo-web-svc
  labels:
    app: live-todo-web
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: live-todo-web