apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-todo-web-deployment
  labels:
    app: live-todo-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: live-todo-web
  template:
    metadata:
      labels:
        app: live-todo-web
    spec:
      initContainers:
      - name: init-public
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ['sh', '-c', 'cp -a /var/www/public/. /shared-public/']
        volumeMounts:
        - name: shared-public
          mountPath: /shared-public
      containers:
      
      - name: php-fpm
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9000

      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: shared-public
          mountPath: /var/www/public
      volumes:
      - name: nginx-conf
        configMap:
          name: live-todo-nginx-conf
      - name: shared-public
        emptyDir: {}