apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: live-todo-ingress
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: live-todo-web-svc
            port:
              number: {{ .Values.service.port }}