apiVersion: v1
kind: Service
metadata:
  name: boom-ott-web-svc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: boom-ott-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: boom-ott-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80