namespace: live-todo-web

replicaCount: 2

image:
  repository: azmattullah/live-todo
  tag: "15"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: todo.avaditech.com
