namespace: boom-ott-web

replicaCount: 2

image:
  repository: azmattullah/boom-ott
  tag: "17"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: todo.avaditech.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls:
    enabled: true
    secretName: boom-ott-tls-secret
