apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-todo-web-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
      
      - name: php-fpm
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9000

      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80